import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { kanit, prompt } from './fonts';
import './globals.css';
import AuthProvider from '@/components/auth-provider';
import ReactQueryProvider from '@/contexts/QueryProvider';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Sample E-Commerce',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${kanit.className} ${prompt.className} antialiased`}>
				<AuthProvider>
					<ReactQueryProvider>{children}</ReactQueryProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
